### ISSUE TITLE
Update AR IND Contacts

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#2845] opened 2023-09-26 17:01 UTC
Hello,
I have attached the updated AR IND Contacts (TAB 2 in excel file) that need to be loaded on ONRR.gov. The ones that are highlighted are the changes that I made.

ONRR.GOV Location:https://onrr.gov/about/contact/paying-contacts?tabs=contacts,indian-accounts-receivable

Thank you,

Jessica
[FederalIndian.Accounts.Receivable.4.19.2023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12730130/FederalIndian.Accounts.Receivable.4.19.2023.xlsx)

**Comment by lpgoldstein** [comment] 2023-09-26 17:17
@Sheetsj ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/paying-contacts?tabs=contacts,indian-accounts-receivable

**Comment by Sheetsj** [comment] 2023-09-26 17:18
Hey, the solids backup was not changed. It should have been changed to Sabrina Tran

**Comment by lpgoldstein** [comment] 2023-09-26 17:22
@Sheetsj sorry about that - we have a duplicate of that card and I only updated one of them. Now it's ready https://dev-onrr-frontend.app.cloud.gov/about/contact/paying-contacts?tabs=contacts,indian-accounts-receivable

**Comment by lpgoldstein** [comment] 2023-09-26 17:26
@Sheetsj live! https://onrr.gov/about/contact/paying-contacts?tabs=contacts,indian-accounts-receivable

**Closed by lpgoldstein** 2023-09-26 17:26 UTC
Labels: Maintenance

**Comment by Sheetsj** [comment] 2023-09-26 17:27
[heart]         Sheets, Jessica E reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, September 26, 2023 5:26:52 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Sheets, Jessica E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update AR IND Contacts (Issue #2845)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Sheetsj<https://github.com/Sheetsj> live! https://onrr.gov/about/contact/paying-contacts?tabs=contacts,indian-accounts-receivable
