### ISSUE TITLE
Alt text for MUI icons

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/onrr.gov-site#2048] opened 2022-07-07 18:48 UTC
Is there a way to add alt text or mark them as decorative?

**Comment by cthomasONRR** [comment] 2022-07-22 12:41
**For the top header icons:** 
![image](https://user-images.githubusercontent.com/72526208/180440145-acbe4032-2c76-4f87-ba00-6792ad238c06.png)
Let's mark these a decorative.

**For the footer icons**, could we mark the Contacts icon as decorative?
![image](https://user-images.githubusercontent.com/72526208/180440296-6768dd3c-b8d9-471f-ae02-ad88e30fb835.png)
Alt Text for social media icons:
- "Facebook logo"
- "Twitter logo"
- "YouTube logo"

**Search icon** in Contact us and top header:
![image](https://user-images.githubusercontent.com/72526208/180440754-4be0eae5-7187-41c1-80aa-6a5721d77f2d.png)
Search Contacts: Can we have alt text for this button that says "Search"?
![image](https://user-images.githubusercontent.com/72526208/180440799-0e7011e2-bd23-4720-b020-315cd61370b7.png)
Top Header: This one can be marked as decorative

**Comment by eelzi-ONRR** [comment] 2024-06-24 19:43
This no longer applies to document type icons - Jeff is working on the svg names for those to apply automatically with the new inline editor, and he'll apply them to the existing icons too. (They can't be marked as decorative or hidden because we don't put the file type in the link label.)

**Comment by eelzi-ONRR** [comment] 2024-06-26 21:00
I think this has already been resolved for the search icon by making it hidden and labeling the form with "Search"

**Comment by eelzi-ONRR** [comment] 2024-06-26 21:03
And I think this has been resolved for the social icons since the images svgs are hidden the the links have been given a label indicating Twitter, Facebook, etc.

@greensomes @cthomasONRR Can you confirm this and my previous comments and close the issue if it's no longer needed? Thanks!

**Comment by greensomes** [comment] 2024-07-25 13:20
@eelzi-ONRR and @cthomasONRR, I have confirmed that the SM icons as well as the download document icons have been addressed. Closing the issue now.

**Closed by greensomes** 2024-07-25 13:20 UTC
Labels: Accessibility, Maintenance, P3: Medium, Tech, CMS
